# 1. Import the dataset

In [26]:
import pandas as pd

# Import the dataset
df = pd.read_csv("RealEstate_Prices.csv")
additional = pd.read_csv('additional_info.csv')
df.columns,additional.columns

(Index(['property id', 'property type', 'neighborhood', 'bedrooms', 'bathrooms',
        'area sq ft', 'year built', 'sale price', 'sale date'],
       dtype='object'),
 Index(['property id', 'distance to amenities mi', 'crime rate',
        'nearby schools', 'demographics population', 'nearby shopping centers',
        'property taxes', 'house condition'],
       dtype='object'))

In [27]:
df.columns = [col.strip().replace(" ", "_").lower() for col in df.columns]
additional.columns = [col.strip().replace(" ", "_").lower() for col in additional.columns]

In [28]:
df.columns,additional.columns

(Index(['property_id', 'property_type', 'neighborhood', 'bedrooms', 'bathrooms',
        'area_sq_ft', 'year_built', 'sale_price', 'sale_date'],
       dtype='object'),
 Index(['property_id', 'distance_to_amenities_mi', 'crime_rate',
        'nearby_schools', 'demographics_population', 'nearby_shopping_centers',
        'property_taxes', 'house_condition'],
       dtype='object'))

In [29]:
merged_df = pd.merge(df,additional,on='property_id',how='inner')
merged_df

,property_id,property_type,neighborhood,bedrooms,bathrooms,area_sq_ft,year_built,sale_price,sale_date,distance_to_amenities_mi,crime_rate,nearby_schools,demographics_population,nearby_shopping_centers,property_taxes,house_condition
0,1001,Apartment,Downtown,3.0,2,1154.0,2001,341218.0,29-09-2020,0.5,Low,3,50000.0,5,10000,Good
1,1002,House,Suburban,4.0,3,2553.0,2014,490564.0,03-04-2021,1.2,Medium,4,60000.0,2,4000,Excellent
2,1003,Condo,Urban,2.0,1,821.0,2008,NaN,15-04-2020,0.3,High,1,40000.0,8,2000,Fair
3,1004,House,Suburban,5.0,4,3018.0,2004,560852.0,25-08-2020,2.5,Low,5,70000.0,3,5000,Excellent
4,1005,Apartment,Downtown,2.0,1,976.0,2013,297985.0,21-05-2022,0.8,Low,3,52000.0,4,3500,Good
5,1006,Condo,Urban,3.0,2,1399.0,2020,1117439.0,09-05-2020,0.6,High,2,45000.0,7,3200,Good
6,1007,House,Rural,6.0,5,3508.0,1999,546970.0,16-05-2021,5.0,Very Low,2,35000.0,1,5500,Excellent
7,1008,Apartment,Suburban,NaN,1,695.0,2022,193182.0,03-02-2022,1.0,Medium,2,48000.0,6,1800,Fair
8,1009,House,Suburban,4.0,3,NaN,2010,479505.0,24-04-2021,2.0,Medium,4,61000.0,2,4200,Excellent
9,1010,Condo,Downtown,2.0,2,961.0,2016,322900.0,10-05-2020,0.4,Low,3,53000.0,5,2700,Good
10,1011,Apartment,Downtown,3.0,2,1144.0,2001,316441.0,06-07-2019,0.5,Low,3,50000.0,5,3000,Good
11,1012,House,Suburban,4.0,3,2534.0,2009,492292.0,11-07-2020,1.2,Medium,4,NaN,2,4000,Excellent
12,1013,Condo,Urban,2.0,1,785.0,2014,NaN,25-08-2020,0.3,High,1,40000.0,8,2000,Fair
13,1014,House,Suburban,5.0,4,3003.0,2004,518357.0,12-03-2020,2.5,Low,5,70000.0,3,5000,NaN
14,1015,Apartment,Downtown,2.0,1,989.0,2018,299637.0,16-11-2022,0.8,Low,3,52000.0,4,3500,Good
15,1016,Condo,Urban,3.0,2,1365.0,2021,1124017.0,29-08-2020,0.6,High,2,45000.0,7,3200,Good
16,1017,House,Rural,6.0,5,3469.0,1993,576509.0,30-09-2020,5.0,Very Low,2,35000.0,1,5500,Excellent
17,1018,Apartment,Suburban,NaN,1,NaN,2022,180891.0,26-06-2021,1.0,Medium,2,48000.0,6,1800,Fair
18,1019,House,Suburban,4.0,3,9729.0,2009,463603.0,02-11-2022,2.0,Medium,4,61000.0,2,4200,Excellent
19,1020,Condo,Downtown,2.0,2,958.0,2020,297056.0,19-10-2018,0.4,Low,3,53000.0,5,2700,Good
20,1021,Apartment,Downtown,3.0,2,1175.0,2007,357830.0,07-05-2019,0.5,Low,3,50000.0,5,3000,Good
21,1022,House,Suburban,4.0,3,2415.0,2005,417554.0,24-05-2022,1.2,Medium,4,NaN,2,4000,Excellent
22,1023,Condo,Urban,2.0,1,834.0,2014,NaN,21-11-2020,0.3,High,1,40000.0,8,10,Fair
23,1024,House,Suburban,5.0,4,3092.0,2002,535300.0,07-06-2021,2.5,Low,5,70000.0,3,5000,Excellent
24,1025,Apartment,Downtown,2.0,1,963.0,2012,317188.0,09-04-2023,0.8,Low,3,52000.0,4,3500,Good
25,1026,Condo,Urban,3.0,2,1452.0,2013,1268442.0,08-03-2021,0.6,High,2,45000.0,7,3200,Good
26,1027,House,Rural,6.0,5,3606.0,2000,563961.0,15-05-2020,5.0,Very Low,2,35000.0,1,5500,NaN
27,1028,Apartment,Suburban,NaN,1,678.0,2016,180512.0,01-08-2021,1.0,Medium,2,48000.0,6,1800,Fair
28,1029,House,Suburban,4.0,3,10393.0,2005,478687.0,24-08-2021,2.0,Medium,4,61000.0,2,4200,Excellent
29,1030,Condo,Downtown,2.0,2,1004.0,2012,281880.0,12-12-2018,0.4,Low,3,53000.0,5,2700,Good
30,1031,Apartment,Downtown,3.0,2,1237.0,2004,357528.0,16-07-2019,0.5,Low,3,50000.0,5,3000,Good
31,1032,House,Suburban,4.0,3,2599.0,2014,420347.0,14-08-2021,1.2,Medium,4,60000.0,2,4000,Excellent
32,1033,Condo,Urban,2.0,1,785.0,2013,NaN,12-09-2019,0.3,High,1,40000.0,8,2000,Fair
33,1034,House,Suburban,5.0,4,2883.0,2004,599377.0,11-05-2020,2.5,Low,5,70000.0,3,5000,Excellent
34,1035,Apartment,Downtown,2.0,1,924.0,2018,349800.0,30-12-2022,0.8,Low,3,52000.0,4,3500,Good
35,1036,Condo,Urban,3.0,2,1390.0,2019,1274015.0,02-08-2020,0.6,High,2,45000.0,7,3200,Good
36,1037,House,Rural,6.0,5,3611.0,2001,576554.0,03-02-2021,5.0,Very Low,2,35000.0,1,5500,Excellent
37,1038,Apartment,Suburban,NaN,1,725.0,2021,165516.0,10-10-2020,1.0,Medium,2,48000.0,6,1800,Fair
38,1039,House,Suburban,4.0,3,9507.0,2004,487318.0,04-10-2022,2.0,Medium,4,61000.0,2,4200,Excellent
39,1040,Condo,Downtown,2.0,2,1001.0,2012,306289.0,29-12-2018,0.4,Low,3,53000.0,5,2700,Good
40,1041,Apartment,Downtown,3.0,2,1190.0,2006,323543.0,17-07-2019,0.5,Low,3,50000.0,5,3000,Good
41,1042,House,Suburban,4.0,3,2431.0,2011,449566.0,12-01-2021,1.2,Medium,4,60000.0,2,4000,Excellent
42,1043,Condo,Urban,2.0,1,770.0,2014,NaN,14-10-2019,0.3,High,1,40000.0,8,2000,NaN
43,1044,House,Suburban,5.0,4,2951.0,1999,595025.0,11-11-2020,2.5,Low,5,NaN,3,5000,Excellent
44,1045,Apartment,Downtown,2.0,1,992.0,2012,304562.0,13-04-2022,0.8,Low,3,52000.0,4,3500,Good
45,1046,Condo,Urban,3.0,2,20003.0,2020,1239005.0,07-11-2021,0.6,High,2,45000.0,7,3200,Good
46,1047,House,Rural,6.0,5,3507.0,1998,577405.0,18-10-2020,5.0,Very Low,2,35000.0,1,5500,Excellent
47,1048,Apartment,Suburban,NaN,1,714.0,2016,180722.0,30-04-2021,1.0,Medium,2,48000.0,6,1800,Fair
48,1049,House,Suburban,4.0,3,50000.0,2003,474391.0,28-06-2022,2.0,Medium,4,61000.0,2,4200,Excellent
49,1050,Condo,Downtown,2.0,2,1047.0,2014,290461.0,05-11-2018,0.4,Low,3,53000.0,5,2700,Good

# 2. Handle missing values

In [31]:
# Check for missing values
missing_values = merged_df.isnull().sum()

# Display missing values
print(missing_values)

property_id                 0
property_type               0
neighborhood                0
bedrooms                    5
bathrooms                   0
area_sq_ft                  2
year_built                  0
sale_price                  5
sale_date                   0
distance_to_amenities_mi    0
crime_rate                  0
nearby_schools              0
demographics_population     3
nearby_shopping_centers     0
property_taxes              0
house_condition             3
dtype: int64

In [48]:
merged_df = merged_df.dropna()

In [49]:
merged_df.isnull().sum()

property_id                 0
property_type               0
neighborhood                0
bedrooms                    0
bathrooms                   0
area_sq_ft                  0
year_built                  0
sale_price                  0
sale_date                   0
distance_to_amenities_mi    0
crime_rate                  0
nearby_schools              0
demographics_population     0
nearby_shopping_centers     0
property_taxes              0
house_condition             0
dtype: int64

# 3. Filter and subset the data

In [47]:
filtered_df = merged_df[(merged_df["sale_date"] >= "2020-01-01") & (merged_df["property_type"] == "Apartment")]
filtered_df

,property_id,property_type,neighborhood,bedrooms,bathrooms,area_sq_ft,year_built,sale_price,sale_date,distance_to_amenities_mi,crime_rate,nearby_schools,demographics_population,nearby_shopping_centers,property_taxes,house_condition
0,1001,Apartment,Downtown,3.000000,2,1154.0,2001,341218.0,29-09-2020,0.5,Low,3,50000.0,5,10000,Good
4,1005,Apartment,Downtown,2.000000,1,976.0,2013,297985.0,21-05-2022,0.8,Low,3,52000.0,4,3500,Good
17,1018,Apartment,Suburban,3.444444,1,NaN,2022,180891.0,26-06-2021,1.0,Medium,2,48000.0,6,1800,Fair
34,1035,Apartment,Downtown,2.000000,1,924.0,2018,349800.0,30-12-2022,0.8,Low,3,52000.0,4,3500,Good
47,1048,Apartment,Suburban,3.444444,1,714.0,2016,180722.0,30-04-2021,1.0,Medium,2,48000.0,6,1800,Fair

# 4. Handle categorical variables

In [50]:
from sklearn.preprocessing import LabelEncoder

categorical_cols = ['property_type',
'neighborhood',
'crime_rate',
'house_condition']

enc = LabelEncoder()

for col in categorical_cols:
    merged_df[col] = enc.fit_transform(merged_df[col])

C:\Users\Vishal77\AppData\Local\Temp\ipykernel_13280\2288591078.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df[col] = enc.fit_transform(merged_df[col])
C:\Users\Vishal77\AppData\Local\Temp\ipykernel_13280\2288591078.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df[col] = enc.fit_transform(merged_df[col])
C:\Users\Vishal77\AppData\Local\Temp\ipykernel_13280\2288591078.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df[col] = enc.fit_transform(merged_df[col])
C:\Users\Vishal77\AppData\Local\Temp\ipykernel_13280\2288591078.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df[col] = enc.fit_transform(merged_df[col])

In [51]:
merged_df.head()

,property_id,property_type,neighborhood,bedrooms,bathrooms,area_sq_ft,year_built,sale_price,sale_date,distance_to_amenities_mi,crime_rate,nearby_schools,demographics_population,nearby_shopping_centers,property_taxes,house_condition
0,1001,0,0,3.0,2,1154.0,2001,341218.0,29-09-2020,0.5,1,3,50000.0,5,10000,2
1,1002,2,2,4.0,3,2553.0,2014,490564.0,03-04-2021,1.2,2,4,60000.0,2,4000,0
3,1004,2,2,5.0,4,3018.0,2004,560852.0,25-08-2020,2.5,1,5,70000.0,3,5000,0
4,1005,0,0,2.0,1,976.0,2013,297985.0,21-05-2022,0.8,1,3,52000.0,4,3500,2
5,1006,1,3,3.0,2,1399.0,2020,1117439.0,09-05-2020,0.6,0,2,45000.0,7,3200,2

In [53]:
aggregated_df = merged_df.groupby("neighborhood").agg({"sale_price": "mean"})
aggregated_df

                sale_price
neighborhood
0             3.176212e+05
1             5.693595e+05
2             4.057098e+05
3             1.204584e+06